In [ ]:
print("hello")

hello

In [ ]:
import pandas as pd # read_csv for load | import
df = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv")
print(df)


df.to_csv("names.csv") # export | save

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [ ]:
# import pandas as pd
# df = pd.read_excel("https://docs.google.com/spreadsheets/d/1r1ppkbQrgNIsY4uuRExo41HTEFtbJ9Qn9MrFVSSVE50/export?format=xlsx")
# print(df)

In [ ]:
import pandas as pd # read_csv for load | import
df = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv")
print(df)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [ ]:
# head -> 5 rows
print(df.head(3))

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345

In [ ]:
print(df.head(-5))

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356

In [ ]:
# tail -> last 5 rows | entry
print(df.tail(-3))

       name  roll no
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [ ]:
# shape
print(df.shape)

(9, 2)

In [ ]:
# rename
# print(df)

df.rename(columns={"name":"full_name","roll no":"stu_id"},inplace=True)

print(df)

  full_name   stu_id
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [ ]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  9 non-null      object
 1   stu_id     9 non-null      int64
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes

In [ ]:
# describe
df.describe().round()

         roll no
count        9.0
mean    141304.0
std     410000.0
min        123.0
25%       1234.0
50%       3333.0
75%      12345.0
max    1234567.0

In [ ]:
# head | tail | info | shape | rename | describe
import pandas as pd

data = {
    "Emp_ID":  [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary":[50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

Operations on coumns

In [ ]:
# select column
print(df["Emp_ID"])

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64

In [ ]:
print(df["Salary"])

0    50000
1    45000
2    60000
3    55000
4    48000
5    52000
Name: Salary, dtype: int64

In [ ]:
# add new column
import numpy as np
df["Increment"] = [500,1000,15000,2000,1200,1400]
print(df)

   Emp_ID  Name Department  Salary  Experience  Increment
0     101  Amit         IT   50000           2        500
1     102  Riya         HR   45000           3       1000
2     103   Raj    Finance   60000           5      15000
3     104  Sara         IT   55000           4       2000
4     105  John      Sales   48000           1       1200
5     106  Neha         HR   52000           3       1400

In [ ]:
# delete column
df.drop("Increment",axis=1,inplace=True)

In [ ]:
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [1]:
import pandas as pd
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Arjun", "Priya", "Karan", "Meena", "David", "Anjali"],
    "Department": ["Marketing", "IT", "HR", "Finance", "Sales", "IT"],
    "Salary": [58000, 62000, 47000, 65000, 51000, 59000],
    "Experience": [3, 5, 2, 6, 2, 4]
}
df = pd.DataFrame(data)

print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [2]:
# select column
print(df["Emp_ID"])

0    201
1    202
2    203
3    204
4    205
5    206
Name: Emp_ID, dtype: int64

In [14]:
# add new column
df["Leaves"] = [10,15,12,9,11,16]
print(df)

   Emp_ID    Name Department  Salary  Experience  Leaves
0     201   Arjun  Marketing   58000           3      10
1     202   Priya         IT   62000           5      15
2     203   Karan         HR   47000           2      12
3     204   Meena    Finance   65000           6       9
4     205   David      Sales   51000           2      11
5     206  Anjali         IT   59000           4      16

In [15]:
# delete column
df.drop("Leaves",axis=1,inplace=True)

print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [22]:
# type
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [29]:
# multi cols delete
df.drop(["Name","Department"],axis=1,inplace=True)

In [30]:
print(df)

   Emp_ID  Salary  Experience
0     201   58000           3
1     202   62000           5
2     203   47000           2
3     204   65000           6
4     205   51000           2
5     206   59000           4

In [32]:
# select multi cols
df[["Emp_ID","Salary"]]

   Emp_ID  Salary
0     201   58000
1     202   62000
2     203   47000
3     204   65000
4     205   51000
5     206   59000

In [37]:
# add new cols
df["Bonus"] = df["Salary"] + 500
print(df)

   Emp_ID  Salary  Experience  bonus  Bonus
0     201   58000           3  58000  58500
1     202   62000           5  62000  62500
2     203   47000           2  47000  47500
3     204   65000           6  65000  65500
4     205   51000           2  51000  51500
5     206   59000           4  59000  59500

In [ ]:
# add new cols -> increment