In [1]:
print("hello")

hello

In [2]:
import pandas as pd # read_csv for load | import
df = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv")
print(df)


df.to_csv("names.csv") # export | save

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [3]:
# import pandas as pd
# df = pd.read_excel("https://docs.google.com/spreadsheets/d/1r1ppkbQrgNIsY4uuRExo41HTEFtbJ9Qn9MrFVSSVE50/export?format=xlsx")
# print(df)

In [4]:
import pandas as pd # read_csv for load | import
df = pd.read_csv("https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file1.csv")
print(df)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [5]:
# head -> 5 rows
print(df.head(3))

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345

In [6]:
print(df.head(-5))

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356

In [7]:
# tail -> last 5 rows | entry
print(df.tail(-3))

       name  roll no
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [8]:
# shape
print(df.shape)

(9, 2)

In [9]:
# rename
# print(df)

df.rename(columns={"name":"full_name","roll no":"stu_id"},inplace=True)

print(df)

  full_name   stu_id
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
5     nitin     1111
6  rajendra     2222
7    girija     3333
8   shailja     4444

In [10]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  9 non-null      object
 1   stu_id     9 non-null      int64
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes

In [11]:
# describe
df.describe().round()

          stu_id
count        9.0
mean    141304.0
std     410000.0
min        123.0
25%       1234.0
50%       3333.0
75%      12345.0
max    1234567.0

In [12]:
# head | tail | info | shape | rename | describe
import pandas as pd

data = {
    "Emp_ID":  [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary":[50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

Operations on coumns

In [13]:
# select column
print(df["Emp_ID"])

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64

In [14]:
print(df["Salary"])

0    50000
1    45000
2    60000
3    55000
4    48000
5    52000
Name: Salary, dtype: int64

In [15]:
# add new column
import numpy as np
df["Increment"] = [500,1000,15000,2000,1200,1400]
print(df)

   Emp_ID  Name Department  Salary  Experience  Increment
0     101  Amit         IT   50000           2        500
1     102  Riya         HR   45000           3       1000
2     103   Raj    Finance   60000           5      15000
3     104  Sara         IT   55000           4       2000
4     105  John      Sales   48000           1       1200
5     106  Neha         HR   52000           3       1400

In [16]:
# delete column
df.drop("Increment",axis=1,inplace=True)

In [17]:
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [18]:
import pandas as pd
data = {
    "Emp_ID": [201, 202, 203, 204, 205, 206],
    "Name": ["Arjun", "Priya", "Karan", "Meena", "David", "Anjali"],
    "Department": ["Marketing", "IT", "HR", "Finance", "Sales", "IT"],
    "Salary": [58000, 62000, 47000, 65000, 51000, 59000],
    "Experience": [3, 5, 2, 6, 2, 4]
}
df = pd.DataFrame(data)

print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [19]:
# select column
print(df["Emp_ID"])

0    201
1    202
2    203
3    204
4    205
5    206
Name: Emp_ID, dtype: int64

In [20]:
# add new column
df["Leaves"] = [10,15,12,9,11,16]
print(df)

   Emp_ID    Name Department  Salary  Experience  Leaves
0     201   Arjun  Marketing   58000           3      10
1     202   Priya         IT   62000           5      15
2     203   Karan         HR   47000           2      12
3     204   Meena    Finance   65000           6       9
4     205   David      Sales   51000           2      11
5     206  Anjali         IT   59000           4      16

In [21]:
# delete column
df.drop("Leaves",axis=1,inplace=True)

print(df)

   Emp_ID    Name Department  Salary  Experience
0     201   Arjun  Marketing   58000           3
1     202   Priya         IT   62000           5
2     203   Karan         HR   47000           2
3     204   Meena    Finance   65000           6
4     205   David      Sales   51000           2
5     206  Anjali         IT   59000           4

In [22]:
# type
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [23]:
# multi cols delete
df.drop(["Name","Department"],axis=1,inplace=True)

In [24]:
print(df)

   Emp_ID  Salary  Experience
0     201   58000           3
1     202   62000           5
2     203   47000           2
3     204   65000           6
4     205   51000           2
5     206   59000           4

In [25]:
# select multi cols
df[["Emp_ID","Salary"]]

   Emp_ID  Salary
0     201   58000
1     202   62000
2     203   47000
3     204   65000
4     205   51000
5     206   59000

In [26]:
# add new cols
df["Bonus"] = df["Salary"] + 500
print(df)

   Emp_ID  Salary  Experience  Bonus
0     201   58000           3  58500
1     202   62000           5  62500
2     203   47000           2  47500
3     204   65000           6  65500
4     205   51000           2  51500
5     206   59000           4  59500

In [27]:
# add new cols -> increment
df["Increment"] = df["Salary"] * 0.1
print(df)

   Emp_ID  Salary  Experience  Bonus  Increment
0     201   58000           3  58500     5800.0
1     202   62000           5  62500     6200.0
2     203   47000           2  47500     4700.0
3     204   65000           6  65500     6500.0
4     205   51000           2  51500     5100.0
5     206   59000           4  59500     5900.0

In [28]:
# task
import pandas as pd

url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"

df = pd.read_json(url)

print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

Operations on rows

In [29]:
import pandas as pd
data = {
    "name":["aman","rahul","priya"],
    "age":[20,21,22]
}
df = pd.DataFrame(data,index=["a","b","c"])
print(df)

    name  age
a   aman   20
b  rahul   21
c  priya   22

In [30]:
# loc
print(df.loc["b"])

name    rahul
age        21
Name: b, dtype: object

In [31]:
# loc
print(df.loc["b","age"])

21

In [32]:
# iloc
print(df.iloc[1])

name    rahul
age        21
Name: b, dtype: object

In [33]:
# iloc
print(df.iloc[1,1])

21

In [34]:
# add -> rows and cols
# update -> rows and cols
# delete -> rows and cols

Filter operations

In [35]:
import pandas as pd

data = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"

df = pd.read_json(data)

print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [36]:
filter_data = df["maths"] > 50

# print(filter_data)

# print(df[filter_data])

print(df[df["maths"] > 50])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [58]:
# english < 60

print(df[df["english"] < 60])

    name  gender  physics  maths  english
3   raja    Male       30     25       40
9   Hema  Female       71     90       23
11   Ram    Male       78     55       47

In [38]:
# physics marks equal to  78
print(df[df["physics"] == 78])

       name  gender  physics  maths  english
7   Kavitha  Female       78     71       67
11      Ram    Male       78     55       47

In [39]:
# physics marks not equal to  78
print(df[df["physics"] != 78])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [40]:
# name equal to Sundar
print(df[df["name"] == "Sundar"])

     name gender  physics  maths  english
6  Sundar   Male       12     67       67

In [41]:
# print users where maths marks > 60 and english marks < 60
print(df[ (df["maths"] > 60) & (df["english"] < 60)])

   name  gender  physics  maths  english
9  Hema  Female       71     90       23

In [42]:
# print users where gender is male and maths marks > 60
print(df[(df["gender"] == "Male") & (df["maths"] > 60)])

       name gender  physics  maths  english
0      arun   Male       88     87       78
1    rajesh   Male       96    100       95
2   moorthy   Male       89     90       70
6    Sundar   Male       12     67       67
12  Murugan   Male       34     89       78

In [43]:
# print users where gender is male or maths marks > 60
print(df[(df["gender"] == "Male") | (df["maths"] > 60)])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [44]:
print(df.query("maths > 60 or english < 60"))

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [45]:
# physics > 60 and english < 60 then =>>> physics
print(df[(df["physics"] > 60) & (df["english"] < 60)]["physics"])

9     71
11    78
Name: physics, dtype: int64

In [46]:
print(df[(df["physics"] > 60) & (df["english"] < 60)][["physics","maths"]])

    physics  maths
9        71     90
11       78     55

Sorting

In [47]:
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [48]:
print(df.sort_values("maths")) # ascending

       name  gender  physics  maths  english
3      raja    Male       30     25       40
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
5     priya  Female       56     46       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
0      arun    Male       88     87       78
13  Jenifer  Female       67     88       90
12  Murugan    Male       34     89       78
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100

In [49]:
print(df.sort_values("maths",ascending=False)) #

       name  gender  physics  maths  english
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0      arun    Male       88     87       78
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
5     priya  Female       56     46       78
4      usha  Female       67     45       78
8    Dinesh    Male       56     45       67
3      raja    Male       30     25       40

In [50]:
print(df.sort_values(["maths","english"])) #

       name  gender  physics  maths  english
3      raja    Male       30     25       40
8    Dinesh    Male       56     45       67
4      usha  Female       67     45       78
5     priya  Female       56     46       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
0      arun    Male       88     87       78
13  Jenifer  Female       67     88       90
12  Murugan    Male       34     89       78
9      Hema  Female       71     90       23
2   moorthy    Male       89     90       70
1    rajesh    Male       96    100       95
10    Gowri  Female      100    100      100

handle missing values

In [59]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"

df = pd.read_json(url)

print(df)

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal        NaN   20.0
2  abhishek    12345.0    NaN
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [60]:
# isnull()
print(df.isnull())

    name  roll no  marks
0  False    False  False
1  False     True  False
2  False    False   True
3  False    False  False
4  False    False  False

In [62]:
# isnull() with sum()
print(df.isnull().sum())

name       0
roll no    1
marks      1
dtype: int64

In [64]:
# isnull() with sum() -> row wise
print(df.isnull().sum(axis=1))

0    0
1    1
2    1
3    0
4    0
dtype: int64

In [65]:
# isnull() with sum() -> cols wise
print(df.isnull().sum(axis=0))

name       0
roll no    1
marks      1
dtype: int64

In [66]:
# drop values by row
print(df.dropna())

      name    roll no  marks
0  dheeraj      123.0   10.0
3  praveen    12356.0   40.0
4   anjali  1234567.0   50.0

In [68]:
# drop null values cols
print(df.dropna())

      name    roll no  marks
0  dheeraj      123.0   10.0
3  praveen    12356.0   40.0
4   anjali  1234567.0   50.0

In [82]:
# fill
print(df.fillna(0))

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal      300.0   20.0
2  abhishek    12345.0  400.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [81]:
# fill with 100
print(df.fillna(100))

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal      300.0   20.0
2  abhishek    12345.0  400.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [75]:
# fill rollno -> 300 | marks -> 400
df["roll no"] = df["roll no"].fillna(300)
print(df)

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal      300.0   20.0
2  abhishek    12345.0    NaN
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [83]:
# fill 400 in marks
df["marks"] = df["marks"].fillna(400)
print(df)

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal      300.0   20.0
2  abhishek    12345.0  400.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [86]:
# alternative option |
df = pd.read_json(url)
df.fillna({"roll no": 200, "marks":500},inplace=True)
print(df)

       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal      200.0   20.0
2  abhishek    12345.0  500.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [90]:
# marks cols -> nan -> mean fillna
df = pd.read_json(url)
mm = df["marks"].mean()
print(mm)
df["marks"] = df["marks"].fillna(mm)
print(df)

30.0
       name    roll no  marks
0   dheeraj      123.0   10.0
1     kunal        NaN   20.0
2  abhishek    12345.0   30.0
3   praveen    12356.0   40.0
4    anjali  1234567.0   50.0

In [ ]:
# numpy -> isnan | fillna | dropna