In [2]:
print("student performance etl")

student performance etl

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student_performance_raw.csv"
df = pd.read_csv(url)
print(df)

   student_id      student_name  gender      age class_section  \
0       ST001     Rahul Sharma     Male       16          10-A
1       ST002       Priya Verma  Female       15          10-A
2       ST003        Amit Kumar       M       16          10-A
3       ST004        Neha Singh  female       15          10-B
4       ST005       Arjun Mehta    Male       16          10-B
5       ST006         Sara Khan       F       15          10-B
6       ST007         Rohan Das    Male       16          10-A
7       ST008       Meera Patel  Female       15          10-C
8       ST009       Kabir Joshi       M       16          10-C
9       ST010        Ananya Roy  Female       15          10-C
10      ST011        Vikram Rao    Male       16          10-A
11      ST012         Isha Nair       F       15          10-B
12      ST013      Dev Malhotra    Male       16          10-C
13      ST014        Pooja Iyer  Female       15          10-A
14      ST015        Karan Gill    Male       16          10-B
15      ST016         Tara Bose  Female       15          10-C
16      ST017       Nikhil Jain       M       16          10-A
17      ST018       Simran Kaur  Female       15          10-B
18      ST019        Aditya Sen    Male       16          10-C
19      ST020       Riya Kapoor       F       15          10-A
20      ST021    Rahul Sharma      Male       16          10-A
21      ST022        Farhan Ali    Male       16          10-B
22      ST023          Maya Das  Female  fifteen          10-C
23      ST024        Om Prakash    Male       16          10-A
24      ST025       Lina George  Female       15          10-B
25      ST026       Yash Thakur    Male       16          10-C
26      ST027        Zoya Ahmed  Female       15          10-A
27      ST028        Manav Shah    Male       16          10-B
28      ST029      Aarav Bansal    Male       16          10-C
29      ST030        Diya Menon  Female       15          10-A
30      ST031        Ira Chawla  Female       15          10-B
31      ST032      Rehan Sheikh       M       16          10-C
32      ST033         Aditi Rao  Female       15          10-A
33      ST034         Samar Roy    Male       16          10-B
34      ST035        Naina Paul  Female       15          10-C
35      ST036      Ishaan Dutta    Male       16          10-A
36      ST037       Tanya Sethi  Female       15          10-B
37      ST038       Ayaan Mirza    Male       16          10-C
38      ST039      Kavya Pillai  Female       15          10-A
39      ST040        Rudra Bose    Male       16          10-B

   study_hours_per_day  math_score  science_score  english_score  \
0                   2         78.0             85             81
1                    5        95.0             91             94
2                    3        65.0             70             68
3                    6        88.0             92             90
4                    4        72.0             75             70
5                    7        98.0             95             97
6                    1        45.0             52             49
7                    5        84.0             87             89
8                    3         NaN             73             76
9                    6        91.0             94             93
10                   2        58.0             62             61
11                  4         79.0             83             80
12                   8        89.0             90             92
13                   5        86.0             88             87
14                   3        67.0             71             69
15                   7        96.0             97             95
16                   2        54.0             58             57
17                   6        90.0             92             91
18                   4        76.0             79             78
19                   5        93.0             95             94
20                   2        78.0             85             81
21               three        74.0             78             76
22                   5        87.0             89             88
23                   4       110.0             82             80
24                   6        -5.0             88             90
25                   3        70.0             74             72
26                   5        92.0             96             94
27                   4        81.0             84             83
28                   2        63.0             66             64
29                   6        89.0             91             90
30                   5        85.0             87             86
31                   4        77.0             80             79
32                   5        94.0             93             96
33                   2        59.0             64             62
34                   7        97.0             96             98
35                   3        68.0             72             70
36                   6        88.0             90             89
37                   4        73.0             76             75
38                   5        91.0             94             92
39                   1        48.0             55             51

    attendance_pct assessment_date
0               92      2025-01-12
1               98      2025-01-12
2               75      2025-01-13
3               96      2025-01-13
4               80      2025-01-14
5               99      2025-01-14
6               60      2025-01-15
7               90      2025-01-15
8               82      2025-01-16
9               97      2025-01-16
10              70      2025-01-17
11              88      2025-01-17
12              95      2025-01-18
13              91      2025-01-18
14              77      2025-01-19
15              98      2025-01-19
16              65      2025-01-20
17              94      2025-01-20
18              85      2025-01-21
19              97      2025-01-21
20              92      2025-01-12
21              84      2025-01-22
22              93      2025-01-22
23              86      2025-01-23
24              92      2025-01-23
25              79    not recorded
26              98      2025/01/24
27              87      2025-01-24
28              72      2025-01-25
29              95      2025-01-25
30              90      2025-01-26
31              84      2025-01-26
32              99      2025-01-27
33              68      2025-01-27
34             100      2025-01-28
35              78      2025-01-28
36              94      2025-01-29
37              81      2025-01-29
38              96      2025-01-30
39              61      2025-01-30

In [12]:
# head -> 5
print(df.head())

  student_id    student_name  gender age class_section study_hours_per_day  \
0      ST001   Rahul Sharma     Male  16          10-A                  2
1      ST002     Priya Verma  Female  15          10-A                   5
2      ST003      Amit Kumar       M  16          10-A                   3
3      ST004      Neha Singh  female  15          10-B                   6
4      ST005     Arjun Mehta    Male  16          10-B                   4

   math_score  science_score  english_score  attendance_pct assessment_date
0        78.0             85             81              92      2025-01-12
1        95.0             91             94              98      2025-01-12
2        65.0             70             68              75      2025-01-13
3        88.0             92             90              96      2025-01-13
4        72.0             75             70              80      2025-01-14

In [14]:
# dtypes
print(df.dtypes)

student_id              object
student_name            object
gender                  object
age                     object
class_section           object
study_hours_per_day     object
math_score             float64
science_score            int64
english_score            int64
attendance_pct           int64
assessment_date         object
dtype: object

In [13]:
# shape
print(df.shape)

(40, 11)

In [15]:
# tail
print(df.tail())

   student_id  student_name  gender age class_section study_hours_per_day  \
35      ST036  Ishaan Dutta    Male  16          10-A                   3
36      ST037   Tanya Sethi  Female  15          10-B                   6
37      ST038   Ayaan Mirza    Male  16          10-C                   4
38      ST039  Kavya Pillai  Female  15          10-A                   5
39      ST040    Rudra Bose    Male  16          10-B                   1

    math_score  science_score  english_score  attendance_pct assessment_date
35        68.0             72             70              78      2025-01-28
36        88.0             90             89              94      2025-01-29
37        73.0             76             75              81      2025-01-29
38        91.0             94             92              96      2025-01-30
39        48.0             55             51              61      2025-01-30

In [16]:
# missing values
print(df.isna())

    student_id  student_name  gender    age  class_section  \
0        False         False   False  False          False
1        False         False   False  False          False
2        False         False   False  False          False
3        False         False   False  False          False
4        False         False   False  False          False
5        False         False   False  False          False
6        False         False   False  False          False
7        False         False   False  False          False
8        False         False   False  False          False
9        False         False   False  False          False
10       False         False   False  False          False
11       False         False   False  False          False
12       False         False   False  False          False
13       False         False   False  False          False
14       False         False   False  False          False
15       False         False   False  False          False
16       False         False   False  False          False
17       False         False   False  False          False
18       False         False   False  False          False
19       False         False   False  False          False
20       False         False   False  False          False
21       False         False   False  False          False
22       False         False   False  False          False
23       False         False   False  False          False
24       False         False   False  False          False
25       False         False   False  False          False
26       False         False   False  False          False
27       False         False   False  False          False
28       False         False   False  False          False
29       False         False   False  False          False
30       False         False   False  False          False
31       False         False   False  False          False
32       False         False   False  False          False
33       False         False   False  False          False
34       False         False   False  False          False
35       False         False   False  False          False
36       False         False   False  False          False
37       False         False   False  False          False
38       False         False   False  False          False
39       False         False   False  False          False

    study_hours_per_day  math_score  science_score  english_score  \
0                 False       False          False          False
1                 False       False          False          False
2                 False       False          False          False
3                 False       False          False          False
4                 False       False          False          False
5                 False       False          False          False
6                 False       False          False          False
7                 False       False          False          False
8                 False        True          False          False
9                 False       False          False          False
10                False       False          False          False
11                False       False          False          False
12                False       False          False          False
13                False       False          False          False
14                False       False          False          False
15                False       False          False          False
16                False       False          False          False
17                False       False          False          False
18                False       False          False          False
19                False       False          False          False
20                False       False          False          False
21                False       False          False          False
22                False       False          False          False
23                False       False          False          False
24                False       False          False          False
25                False       False          False          False
26                False       False          False          False
27                False       False          False          False
28                False       False          False          False
29                False       False          False          False
30                False       False          False          False
31                False       False          False          False
32                False       False          False          False
33                False       False          False          False
34                False       False          False          False
35                False       False          False          False
36                False       False          False          False
37                False       False          False          False
38                False       False          False          False
39                False       False          False          False

    attendance_pct  assessment_date
0            False            False
1            False            False
2            False            False
3            False            False
4            False            False
5            False            False
6            False            False
7            False            False
8            False            False
9            False            False
10           False            False
11           False            False
12           False            False
13           False            False
14           False            False
15           False            False
16           False            False
17           False            False
18           False            False
19           False            False
20           False            False
21           False            False
22           False            False
23           False            False
24           False            False
25           False            False
26           False            False
27           False            False
28           False            False
29           False            False
30           False            False
31           False            False
32           False            False
33           False            False
34           False            False
35           False            False
36           False            False
37           False            False
38           False            False
39           False            False

In [17]:
# missing values sum print
print(df.isna().sum())

student_id             0
student_name           0
gender                 0
age                    0
class_section          0
study_hours_per_day    0
math_score             1
science_score          0
english_score          0
attendance_pct         0
assessment_date        0
dtype: int64

In [23]:
# duplicate values
print(df.duplicated(subset='student_id'))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
dtype: bool

In [24]:
# duplicates values sum print
print(df.duplicated(subset='student_id').sum())

0

In [25]:
# keep a copy of original df
raw_df = df.copy()

In [36]:
# Transform
# student_id -> string | student_name -> string | gender -> string
# age -> int | study_hours_per_day  -> float
# assessment_date  -> date

# method 1
df['student_id'] = df['student_id'].astype('string')
df['student_name'] = df['student_name'].astype('string')
df['gender'] = df['gender'].astype('string')

# method 2
cols = ['student_id','student_name','gender']
for col in cols:
  df[col] = df[col].astype('string')

In [35]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [37]:
df['age']

0     16.0
1     15.0
2     16.0
3     15.0
4     16.0
5     15.0
6     16.0
7     15.0
8     16.0
9     15.0
10    16.0
11    15.0
12    16.0
13    15.0
14    16.0
15    15.0
16    16.0
17    15.0
18    16.0
19    15.0
20    16.0
21    16.0
22     NaN
23    16.0
24    15.0
25    16.0
26    15.0
27    16.0
28    16.0
29    15.0
30    15.0
31    16.0
32    15.0
33    16.0
34    15.0
35    16.0
36    15.0
37    16.0
38    15.0
39    16.0
Name: age, dtype: float64

In [38]:
df['assessment_date'] = pd.to_datetime(df['assessment_date'], errors='coerce')

In [39]:
df['assessment_date']

0    2025-01-12
1    2025-01-12
2    2025-01-13
3    2025-01-13
4    2025-01-14
5    2025-01-14
6    2025-01-15
7    2025-01-15
8    2025-01-16
9    2025-01-16
10   2025-01-17
11   2025-01-17
12   2025-01-18
13   2025-01-18
14   2025-01-19
15   2025-01-19
16   2025-01-20
17   2025-01-20
18   2025-01-21
19   2025-01-21
20   2025-01-12
21   2025-01-22
22   2025-01-22
23   2025-01-23
24   2025-01-23
25          NaT
26          NaT
27   2025-01-24
28   2025-01-25
29   2025-01-25
30   2025-01-26
31   2025-01-26
32   2025-01-27
33   2025-01-27
34   2025-01-28
35   2025-01-28
36   2025-01-29
37   2025-01-29
38   2025-01-30
39   2025-01-30
Name: assessment_date, dtype: datetime64[ns]

In [40]:
df['gender']

0       Male
1     Female
2          M
3     female
4       Male
5          F
6       Male
7     Female
8          M
9     Female
10      Male
11         F
12      Male
13    Female
14      Male
15    Female
16         M
17    Female
18      Male
19         F
20      Male
21      Male
22    Female
23      Male
24    Female
25      Male
26    Female
27      Male
28      Male
29    Female
30    Female
31         M
32    Female
33      Male
34    Female
35      Male
36    Female
37      Male
38    Female
39      Male
Name: gender, dtype: string

In [45]:
df['gender'] = df['gender'].replace(
    {"M":"Male","MALE":"Male","F":"Female","FEMALE":"Female",'female':'Female'})

In [46]:
df['gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: string